// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package systems.soapbox.wirerecord;

public final class OmbudsWireProtos {
  private OmbudsWireProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BulletinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ombwire.Bulletin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>optional .ombwire.Location location = 3;</code>
     */
    boolean hasLocation();
    /**
     * <code>optional .ombwire.Location location = 3;</code>
     */
    systems.soapbox.wirerecord.OmbudsWireProtos.Location getLocation();
    /**
     * <code>optional .ombwire.Location location = 3;</code>
     */
    systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder getLocationOrBuilder();
  }
  /**
   * Protobuf type {@code ombwire.Bulletin}
   */
  public static final class Bulletin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ombwire.Bulletin)
      BulletinOrBuilder {
    // Use Bulletin.newBuilder() to construct.
    private Bulletin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Bulletin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Bulletin defaultInstance;
    public static Bulletin getDefaultInstance() {
      return defaultInstance;
    }

    public Bulletin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Bulletin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(systems.soapbox.wirerecord.OmbudsWireProtos.Location.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Bulletin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Bulletin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin.class, systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin.Builder.class);
    }

    public static com.google.protobuf.Parser<Bulletin> PARSER =
        new com.google.protobuf.AbstractParser<Bulletin>() {
      public Bulletin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bulletin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Bulletin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>required string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private systems.soapbox.wirerecord.OmbudsWireProtos.Location location_;
    /**
     * <code>optional .ombwire.Location location = 3;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ombwire.Location location = 3;</code>
     */
    public systems.soapbox.wirerecord.OmbudsWireProtos.Location getLocation() {
      return location_;
    }
    /**
     * <code>optional .ombwire.Location location = 3;</code>
     */
    public systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder getLocationOrBuilder() {
      return location_;
    }

    private void initFields() {
      message_ = "";
      timestamp_ = 0L;
      location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLocation()) {
        if (!getLocation().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, location_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, location_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ombwire.Bulletin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ombwire.Bulletin)
        systems.soapbox.wirerecord.OmbudsWireProtos.BulletinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Bulletin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Bulletin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin.class, systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin.Builder.class);
      }

      // Construct using systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (locationBuilder_ == null) {
          location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Bulletin_descriptor;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin getDefaultInstanceForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin.getDefaultInstance();
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin build() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin buildPartial() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin result = new systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin) {
          return mergeFrom((systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin other) {
        if (other == systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (hasLocation()) {
          if (!getLocation().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (systems.soapbox.wirerecord.OmbudsWireProtos.Bulletin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private systems.soapbox.wirerecord.OmbudsWireProtos.Location location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          systems.soapbox.wirerecord.OmbudsWireProtos.Location, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder, systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder> locationBuilder_;
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public systems.soapbox.wirerecord.OmbudsWireProtos.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public Builder setLocation(systems.soapbox.wirerecord.OmbudsWireProtos.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public Builder setLocation(
          systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public Builder mergeLocation(systems.soapbox.wirerecord.OmbudsWireProtos.Location value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              location_ != systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance()) {
            location_ =
              systems.soapbox.wirerecord.OmbudsWireProtos.Location.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
          onChanged();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder getLocationBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      public systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_;
        }
      }
      /**
       * <code>optional .ombwire.Location location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          systems.soapbox.wirerecord.OmbudsWireProtos.Location, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder, systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              systems.soapbox.wirerecord.OmbudsWireProtos.Location, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder, systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ombwire.Bulletin)
    }

    static {
      defaultInstance = new Bulletin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ombwire.Bulletin)
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ombwire.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double lat = 1;</code>
     */
    boolean hasLat();
    /**
     * <code>required double lat = 1;</code>
     */
    double getLat();

    /**
     * <code>required double lon = 2;</code>
     */
    boolean hasLon();
    /**
     * <code>required double lon = 2;</code>
     */
    double getLon();

    /**
     * <code>required double h = 3;</code>
     */
    boolean hasH();
    /**
     * <code>required double h = 3;</code>
     */
    double getH();
  }
  /**
   * Protobuf type {@code ombwire.Location}
   *
   * <pre>
   * A single WGS84 Datum
   * </pre>
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ombwire.Location)
      LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              lat_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lon_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              h_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              systems.soapbox.wirerecord.OmbudsWireProtos.Location.class, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LAT_FIELD_NUMBER = 1;
    private double lat_;
    /**
     * <code>required double lat = 1;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double lat = 1;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int LON_FIELD_NUMBER = 2;
    private double lon_;
    /**
     * <code>required double lon = 2;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double lon = 2;</code>
     */
    public double getLon() {
      return lon_;
    }

    public static final int H_FIELD_NUMBER = 3;
    private double h_;
    /**
     * <code>required double h = 3;</code>
     */
    public boolean hasH() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double h = 3;</code>
     */
    public double getH() {
      return h_;
    }

    private void initFields() {
      lat_ = 0D;
      lon_ = 0D;
      h_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasH()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, h_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, h_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(systems.soapbox.wirerecord.OmbudsWireProtos.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ombwire.Location}
     *
     * <pre>
     * A single WGS84 Datum
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ombwire.Location)
        systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                systems.soapbox.wirerecord.OmbudsWireProtos.Location.class, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder.class);
      }

      // Construct using systems.soapbox.wirerecord.OmbudsWireProtos.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        h_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Location_descriptor;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Location getDefaultInstanceForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Location build() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Location buildPartial() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Location result = new systems.soapbox.wirerecord.OmbudsWireProtos.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lon_ = lon_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.h_ = h_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof systems.soapbox.wirerecord.OmbudsWireProtos.Location) {
          return mergeFrom((systems.soapbox.wirerecord.OmbudsWireProtos.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(systems.soapbox.wirerecord.OmbudsWireProtos.Location other) {
        if (other == systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance()) return this;
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        if (other.hasH()) {
          setH(other.getH());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLon()) {
          
          return false;
        }
        if (!hasH()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        systems.soapbox.wirerecord.OmbudsWireProtos.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (systems.soapbox.wirerecord.OmbudsWireProtos.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double lat_ ;
      /**
       * <code>required double lat = 1;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double lat = 1;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>required double lat = 1;</code>
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000001;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lat = 1;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0D;
        onChanged();
        return this;
      }

      private double lon_ ;
      /**
       * <code>required double lon = 2;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double lon = 2;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>required double lon = 2;</code>
       */
      public Builder setLon(double value) {
        bitField0_ |= 0x00000002;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lon = 2;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lon_ = 0D;
        onChanged();
        return this;
      }

      private double h_ ;
      /**
       * <code>required double h = 3;</code>
       */
      public boolean hasH() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double h = 3;</code>
       */
      public double getH() {
        return h_;
      }
      /**
       * <code>required double h = 3;</code>
       */
      public Builder setH(double value) {
        bitField0_ |= 0x00000004;
        h_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double h = 3;</code>
       */
      public Builder clearH() {
        bitField0_ = (bitField0_ & ~0x00000004);
        h_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ombwire.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ombwire.Location)
  }

  public interface EndorsementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ombwire.Endorsement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes bid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    boolean hasBid();
    /**
     * <code>required bytes bid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    com.google.protobuf.ByteString getBid();

    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code ombwire.Endorsement}
   */
  public static final class Endorsement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ombwire.Endorsement)
      EndorsementOrBuilder {
    // Use Endorsement.newBuilder() to construct.
    private Endorsement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Endorsement(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Endorsement defaultInstance;
    public static Endorsement getDefaultInstance() {
      return defaultInstance;
    }

    public Endorsement getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Endorsement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              bid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Endorsement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Endorsement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement.class, systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement.Builder.class);
    }

    public static com.google.protobuf.Parser<Endorsement> PARSER =
        new com.google.protobuf.AbstractParser<Endorsement>() {
      public Endorsement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Endorsement(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Endorsement> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString bid_;
    /**
     * <code>required bytes bid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes bid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    public com.google.protobuf.ByteString getBid() {
      return bid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      bid_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ombwire.Endorsement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ombwire.Endorsement)
        systems.soapbox.wirerecord.OmbudsWireProtos.EndorsementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Endorsement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Endorsement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement.class, systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement.Builder.class);
      }

      // Construct using systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_ombwire_Endorsement_descriptor;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement getDefaultInstanceForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement.getDefaultInstance();
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement build() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement buildPartial() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement result = new systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement) {
          return mergeFrom((systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement other) {
        if (other == systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement.getDefaultInstance()) return this;
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBid()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (systems.soapbox.wirerecord.OmbudsWireProtos.Endorsement) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString bid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes bid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public com.google.protobuf.ByteString getBid() {
        return bid_;
      }
      /**
       * <code>required bytes bid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public Builder setBid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = getDefaultInstance().getBid();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ombwire.Endorsement)
    }

    static {
      defaultInstance = new Endorsement(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ombwire.Endorsement)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ombwire_Bulletin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ombwire_Bulletin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ombwire_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ombwire_Location_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ombwire_Endorsement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ombwire_Endorsement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013types.proto\022\007ombwire\"S\n\010Bulletin\022\017\n\007me" +
      "ssage\030\001 \002(\t\022\021\n\ttimestamp\030\002 \002(\004\022#\n\010locati" +
      "on\030\003 \001(\0132\021.ombwire.Location\"/\n\010Location\022" +
      "\013\n\003lat\030\001 \002(\001\022\013\n\003lon\030\002 \002(\001\022\t\n\001h\030\003 \002(\001\"-\n\013" +
      "Endorsement\022\013\n\003bid\030\001 \002(\014\022\021\n\ttimestamp\030\002 " +
      "\002(\004B.\n\032systems.soapbox.wirerecordB\020Ombud" +
      "sWireProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ombwire_Bulletin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ombwire_Bulletin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ombwire_Bulletin_descriptor,
        new java.lang.String[] { "Message", "Timestamp", "Location", });
    internal_static_ombwire_Location_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ombwire_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ombwire_Location_descriptor,
        new java.lang.String[] { "Lat", "Lon", "H", });
    internal_static_ombwire_Endorsement_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ombwire_Endorsement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ombwire_Endorsement_descriptor,
        new java.lang.String[] { "Bid", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
