# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wirebulletin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wirebulletin.proto',
  package='',
  serialized_pb='\n\x12wirebulletin.proto\"A\n\x0cWireBulletin\x12\r\n\x05\x62oard\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x42\x14\x42\x12WireBulletinProtos')




_WIREBULLETIN = _descriptor.Descriptor(
  name='WireBulletin',
  full_name='WireBulletin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board', full_name='WireBulletin.board', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='WireBulletin.message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='WireBulletin.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['WireBulletin'] = _WIREBULLETIN

class WireBulletin(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WIREBULLETIN

  # @@protoc_insertion_point(class_scope:WireBulletin)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\022WireBulletinProtos')
# @@protoc_insertion_point(module_scope)
